### ISSUE TITLE
I think you are misclassifying the paid model as Saas.

### ISSUE THREAD

**Issue by ccuser44** [evoincorp/commander#5]
It actually isn't called saas.

Definition of saas (Source Wikipedia)
```
Software as a service (SaaS) is a software licensing and delivery model in which software is licensed
on a subscription basis and is centrally hosted.
SaaS is also known as "on-demand software" and Web-based/Web-hosted software.

SaaS is considered to be part of cloud computing, along with infrastructure as a service (IaaS),
platform as a service (PaaS), desktop as a service (DaaS), managed software as a service (MSaaS),
mobile backend as a service (MBaaS), datacenter as a service (DCaaS),
and information technology management as a service (ITMaaS). 
```

So Saas means cloud computing where the majority of the code runs on a remote server and only a small client interfaces with it.

So it really isn't Saas but more of a pay to get premium version model.

Also I think you should make the paid model time 1 week instead of 1 month to deter leakers from leaking it to the public. And make an anti-leak policy so if someone leaks it they cannot get access to the private repo anymore.

**Comment by ccuser44** [comment]
I myself was a bit confused with the SaaS naming and I thought that the majority of the code would run on a web server and the client on Roblox would interface with the code.

**Comment by Marimariius** [comment]
it's considered to be part of cloud computing and doesn't only mean that. Windows is SaaS and there's no cloud computing going on in the actual OS (aside from analytics)

**Comment by 7kayoh** [comment]
Perhaps, meant to say Software as a Subscription, but Commander is also Software as a Service (quasi-SaaS).

The web dashboard is an example of quasi-SaaS (offers both web and installables),

**Comment by 7kayoh** [comment]
> Also I think you should make the paid model time 1 week instead of 1 month to deter leakers from leaking it to the public. And make an anti-leak policy so if someone leaks it they cannot get access to the private repo anymore.

We do not plan to make the sponsorware business model so it requires a week of sponsorship instead of a month, this is because we are not going to ship updates with new features and improvements per every week, but instead per month.

On the concern about potential leakers, we will be setting up an anti-leak policy to push away leakers to leaking, but the chance of it working 100% is impossible. However, this is more for supporting the developers, not actually for profit at first. Instead, our web dashboard is for profit, by subscribing any of the hosting plans, you have access to the web dashboard hosted by our servers, with a few special features bundled. The special version of the web dashboard used by our upcoming subscription services will remain close source, but the regular one without any paid-exclusive features will be open source

**Comment by ccuser44** [comment]
> Perhaps, meant to say Software as a Subscription, but Commander is also Software as a Service (quasi-SaaS).
> 
> The web dashboard is an example of quasi-SaaS (offers both web and installables),

Hmm .. maybe but you still should call the private repo something else than SaaS.

**Comment by 7kayoh** [comment]
> Erm. You not sure if you refer to the back end or the front end code. Please keep the front end code as FOSS.

I believe you have made a misconception there. The version used for the web dashboard hosting contains a few more exclusive features and we are not willing to open source that part as that is pretty much the only advantage for the hosting services.

but the regular dashboard without the exclusive features is open source under the MIT license.

**Comment by 7kayoh** [comment]
> Hmm .. perhaps but you still should call the private repo something else than SaaS.

Perhaps, but considering it is a subscription, it still falls under the SaaS category.
